# generated by datamodel-codegen:
#   filename:  HealthMetrics.json
#   timestamp: 2026-03-10T07:16:59+00:00

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field


class HealthMetrics(BaseModel):
    score: float = Field(
        ..., description='Aggregated health score (0-100)', ge=0.0, le=100.0
    )
    trend: Literal['up', 'down', 'stable'] = Field(
        ..., description='Directional health trend'
    )
    momentum: float = Field(..., description='Rate of change per day')
    resilience: float = Field(..., description='Ability to recover from health dips')
    severity: Literal['CRITICAL', 'WARNING', 'INFO', 'OPTIMAL'] = Field(
        ..., description='CIA 3-tier risk severity classification'
    )
    last_assessment: AwareDatetime = Field(
        ..., description='ISO-8601 timestamp of last analysis'
    )
