# generated by datamodel-codegen:
#   filename:  IntelligenceObservation.json
#   timestamp: 2026-03-10T07:58:19+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, constr


class Vector(BaseModel):
    dimension: str = Field(..., description='e.g., DomainMatch, ResourceAvailability')
    raw_value: float = Field(..., description='Raw calculated value', ge=0.0, le=1.0)
    weight: float = Field(
        ..., description='Importance multiplier for this use-case', ge=0.0
    )
    score: float = Field(..., description='raw_value * weight')


class IntelligenceScore(BaseModel):
    overall_score: float = Field(
        ..., description='Final aggregated 0-100 win probability', ge=0.0, le=100.0
    )
    confidence: float = Field(
        ..., description='Statistical confidence in the prediction', ge=0.0, le=1.0
    )
    vectors: list[Vector] = Field(
        ..., description='The individual factors making up the score'
    )
    is_go: bool = Field(..., description='True if overall_score > threshold')
    assessed_at: AwareDatetime


class IntelligenceObservation(BaseModel):
    observation_id: str = Field(
        ..., description='Unique identifier (hash or source ID)'
    )
    source_type: Literal[
        'MEDIA',
        'CODE_REPO',
        'FINANCIAL',
        'GOVERNMENT_DATA',
        'LEGAL_TENDER',
        'CYBER_SIGNAL',
    ]
    title: str
    content_summary: str
    actor_name: str = Field(..., description='e.g. Agency name or Vendor name')
    metadata: dict[constr(pattern=r'^(.*)$'), Any] = Field(
        ..., description='Dynamic fields like budget, github_stars, or CVE_id'
    )
    timestamp: AwareDatetime
    source_url: str | None = None
    intelligence_score: IntelligenceScore | None = Field(
        None, description='Aggregated intelligence assessment'
    )
