# generated by datamodel-codegen:
#   filename:  AgentWorkflowEnvelope.json
#   timestamp: 2026-03-18T14:06:14+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field


class AgentWorkflowEnvelope(BaseModel):
    workflow_id: str = Field(
        ..., description='Stable workflow identifier for orchestration lineage.'
    )
    workflow_type: Literal['research', 'delivery', 'audit', 'debate'] = Field(
        ..., description='Workflow families allowed for the scoped orchestration layer.'
    )
    current_phase: Literal['discover', 'define', 'develop', 'deliver'] = Field(
        ...,
        description='Canonical orchestration phases, narrowed for orchestrator/librechat/snout usage only.',
    )
    participants: list[
        Literal[
            'Claude',
            'Gemini',
            'DeepSeek',
            'Grok',
            'RLM',
            'User',
            'System',
            'Orchestrator',
        ]
        | str
    ] = Field(
        ...,
        description='Participants involved in the current workflow envelope.',
        min_length=1,
    )
    primary_surface: Literal['widgetdc-orchestrator', 'widgetdc-librechat', 'snout'] = (
        Field(
            ...,
            description='Primary consumer/runtime that owns this workflow envelope.',
        )
    )
    flow_ref: Literal['core-flow-1', 'core-flow-2', 'core-flow-3'] = Field(
        ..., description='Canonical LIN-165 flow strengthened by this workflow.'
    )
    scorecard_ref: str = Field(
        ...,
        description='Reference to the decision-quality scorecard batch or evidence packet.',
    )
    reasoning_lineage_visible: bool = Field(
        ...,
        description='Whether the workflow lineage may be surfaced in LibreChat or other approved consumers.',
    )
    quorum_consensus: bool | None = Field(
        None,
        description='Set when a workflow requires explicit agreement before progressing.',
    )
    compute_mode: Literal['standard', 'extreme'] | None = Field(
        'standard',
        description='Allocated compute intensity for the current workflow phase.',
    )
    phase_parameters: dict[str, Any] | None = Field(
        None,
        description='Optimized parameters for multi-step agentic execution (Adoption: OpenAI Phase Pattern). Reduces token usage via targeted tool discovery.',
    )
    started_at: AwareDatetime = Field(..., description='Workflow start timestamp.')
    updated_at: AwareDatetime = Field(
        ..., description='Last workflow state update timestamp.'
    )
