# generated by datamodel-codegen:
#   filename:  SalienceVector.json
#   timestamp: 2026-03-10T07:46:40+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SalienceVector(BaseModel):
    dimension: str = Field(..., description='e.g., DomainMatch, ResourceAvailability')
    raw_value: float = Field(..., description='Raw calculated value', ge=0.0, le=1.0)
    weight: float = Field(
        ..., description='Importance multiplier for this use-case', ge=0.0
    )
    score: float = Field(..., description='raw_value * weight')
