# generated by datamodel-codegen:
#   filename:  WinProbabilityScore.json
#   timestamp: 2026-03-10T07:46:43+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field


class Vector(BaseModel):
    dimension: str = Field(..., description='e.g., DomainMatch, ResourceAvailability')
    raw_value: float = Field(..., description='Raw calculated value', ge=0.0, le=1.0)
    weight: float = Field(
        ..., description='Importance multiplier for this use-case', ge=0.0
    )
    score: float = Field(..., description='raw_value * weight')


class WinProbabilityScore(BaseModel):
    overall_score: float = Field(
        ..., description='Final aggregated 0-100 win probability', ge=0.0, le=100.0
    )
    confidence: float = Field(
        ..., description='Statistical confidence in the prediction', ge=0.0, le=1.0
    )
    vectors: list[Vector] = Field(
        ..., description='The individual factors making up the score'
    )
    is_go: bool = Field(..., description='True if overall_score > threshold')
    assessed_at: AwareDatetime
