import { Static, Type } from '@sinclair/typebox'
import {
  LauncherEvidenceFamily,
  LauncherEvidenceStatus,
} from './launcher-evidence-packet.js'

export const BackendGovernanceEvidenceItemResponseV1 = Type.Object({
  id: Type.String({
    minLength: 1,
    description: 'Stable evidence item id.',
  }),
  summary: Type.String({
    minLength: 1,
    description: 'Short evidence summary consumed by launcher-like surfaces.',
  }),
  score: Type.Optional(Type.Number({
    minimum: 0,
    description: 'Relative evidence relevance score when available.',
  })),
  title: Type.Optional(Type.String()),
  source_type: Type.Optional(Type.String()),
}, {
  $id: 'BackendGovernanceEvidenceItemResponseV1',
  description: 'Minimal evidence item shape returned inside backend governance evidence packet responses.',
})

export type BackendGovernanceEvidenceItemResponseV1 = Static<typeof BackendGovernanceEvidenceItemResponseV1>

export const BackendGovernanceEvidenceFamilyResponseV1 = Type.Object({
  family: LauncherEvidenceFamily,
  status: Type.Optional(LauncherEvidenceStatus),
  summary: Type.String({
    minLength: 1,
    description: 'Family summary consumed by launcher-like surfaces.',
  }),
  evidence_items: Type.Array(BackendGovernanceEvidenceItemResponseV1),
}, {
  $id: 'BackendGovernanceEvidenceFamilyResponseV1',
  description: 'Minimal family packet returned inside backend governance evidence packet responses.',
})

export type BackendGovernanceEvidenceFamilyResponseV1 = Static<typeof BackendGovernanceEvidenceFamilyResponseV1>

export const BackendGovernanceEvidencePacketGovernanceV1 = Type.Object({
  blocking_reasons: Type.Array(Type.String(), {
    description: 'Coverage or governance blockers detected while composing the packet.',
  }),
  promotion_status: Type.Optional(Type.Union([
    Type.Literal('not_promoted'),
    Type.Literal('blocked'),
  ])),
  can_promote: Type.Optional(Type.Boolean()),
}, {
  $id: 'BackendGovernanceEvidencePacketGovernanceV1',
  description: 'Governance subsection of backend evidence packet responses.',
})

export type BackendGovernanceEvidencePacketGovernanceV1 = Static<typeof BackendGovernanceEvidencePacketGovernanceV1>

export const BackendGovernanceEvidencePacketResponseV1 = Type.Object({
  packet_id: Type.String({
    minLength: 1,
    description: 'Stable packet id for routing and read-back.',
  }),
  tri_source_ready: Type.Boolean({
    description: 'True when enough evidence exists for multi-signal launcher use.',
  }),
  governance: BackendGovernanceEvidencePacketGovernanceV1,
  families: Type.Array(BackendGovernanceEvidenceFamilyResponseV1, {
    minItems: 1,
    description: 'Family evidence summaries returned by backend governance surfaces.',
  }),
  question: Type.Optional(Type.String()),
  domain: Type.Optional(Type.String()),
  created_at: Type.Optional(Type.String({ format: 'date-time' })),
  evidence_refs: Type.Optional(Type.Array(Type.String())),
}, {
  $id: 'backend.governance.evidence_packet.response.v1',
  description: 'Shared backend governance evidence packet response contract for launcher-like consumers.',
})

export type BackendGovernanceEvidencePacketResponseV1 = Static<typeof BackendGovernanceEvidencePacketResponseV1>

export const ArtifactChallengeOutcomeV1 = Type.Object({
  trace_id: Type.String({
    minLength: 1,
    description: 'Trace id or outcome id emitted for the challenge action.',
  }),
  status: Type.Literal('CHALLENGED'),
  reason: Type.String({
    minLength: 1,
    description: 'Challenge reason supplied by the surface or operator.',
  }),
  evidence_uri: Type.Optional(Type.Union([Type.String({ format: 'uri' }), Type.Null()])),
}, {
  $id: 'ArtifactChallengeOutcomeV1',
  description: 'Outcome payload generated by artifact challenge requests.',
})

export type ArtifactChallengeOutcomeV1 = Static<typeof ArtifactChallengeOutcomeV1>

export const ArtifactChallengeGraphWriteV1 = Type.Object({
  outcome_label: Type.Literal('Outcome'),
  relation_type: Type.Literal('CHALLENGES'),
  target_identity: Type.String({
    minLength: 1,
    description: 'Target artifact identity for the challenge relation.',
  }),
}, {
  $id: 'ArtifactChallengeGraphWriteV1',
  description: 'Graph write instruction for artifact challenge envelopes.',
})

export type ArtifactChallengeGraphWriteV1 = Static<typeof ArtifactChallengeGraphWriteV1>

export const ArtifactChallengeEnvelopeV1 = Type.Object({
  tool: Type.Literal('artifacts.challenge'),
  artifact_id: Type.String({
    minLength: 1,
  }),
  artifact_slug: Type.Optional(Type.String({
    minLength: 1,
    description: 'Compatibility metadata field retained during migration.',
  })),
  outcome: ArtifactChallengeOutcomeV1,
  graph_write: ArtifactChallengeGraphWriteV1,
}, {
  $id: 'artifact.challenge.envelope.v1',
  description: 'Shared artifact challenge envelope emitted by surfaces before canonical backend persistence.',
})

export type ArtifactChallengeEnvelopeV1 = Static<typeof ArtifactChallengeEnvelopeV1>

export const ArtifactRequestReviewGraphWriteV1 = Type.Object({
  type: Type.Literal('ConstructionRequest'),
  request_kind: Type.Literal('REVIEW'),
  requested_by: Type.String({
    minLength: 1,
    description: 'Actor requesting review.',
  }),
  artifact_id: Type.String({
    minLength: 1,
  }),
}, {
  $id: 'ArtifactRequestReviewGraphWriteV1',
  description: 'Graph write instruction for artifact request-review envelopes.',
})

export type ArtifactRequestReviewGraphWriteV1 = Static<typeof ArtifactRequestReviewGraphWriteV1>

export const ArtifactRequestReviewEnvelopeV1 = Type.Object({
  tool: Type.Literal('artifacts.action'),
  action: Type.Literal('request-review'),
  artifact_id: Type.String({
    minLength: 1,
  }),
  graph_write: ArtifactRequestReviewGraphWriteV1,
}, {
  $id: 'artifact.request_review.envelope.v1',
  description: 'Shared artifact request-review envelope emitted by surfaces before canonical backend persistence.',
})

export type ArtifactRequestReviewEnvelopeV1 = Static<typeof ArtifactRequestReviewEnvelopeV1>
